version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: online_learning
      DB_PASS: YJVWtrBc
      DB_NAME: online_learning_db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: fljHZyRy
      MYSQL_USER: online_learning
      MYSQL_PASSWORD: YJVWtrBc
      MYSQL_DATABASE: online_learning_db
    ports:
      - "3306:3306"
    volumes:
      - "./initializer/civ-ecom.sql:/docker-entrypoint-initdb.d/1.sql"

  websetup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
    restart: "no"
    #entrypoint: ["bash", "-c", "sleep 10 && adonis key:generate && adonis migration:run && adonis seed"]
